version: '3'
services:
  database:
    image: mongo
    container_name: loadingProblem_DB
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE}"
    volumes:
      - mongo-db:/data/db/mongodb
    ports:
      - '${DB_PORT}:${DB_PORT}'
  
volumes:
  mongo-db: